kind: Deployment
apiVersion: apps/v1
metadata:
  name: supply-chain-demo-app
  namespace: github-actions-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supply-chain-demo-app
  template:
    metadata:
      labels:
        app: supply-chain-demo-app
    spec:
      containers:
        - name: supply-chain-demo-app
          image: quay.io/sdouglas/spring-app:${SHA}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          resources:
            requests:
              memory: "180Mi"
              cpu: "10m"
---
kind: Service
apiVersion: v1
metadata:
  name: my-java-springboot-svc
  namespace: github-actions-demo
spec:
  ports:
    - name: http-8081
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: supply-chain-demo-app