apiVersion: v1
kind: Namespace
metadata:
  name: github-actions-demo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-actions-demo
  namespace: github-actions-demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: github-actions-demo
  namespace: github-actions-demo
rules:
  # List services
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - list
      - get
      - patch
      - create
  # List, get, and patch deployments
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - create
      - list
      - get
      - patch
  # List replicasets. This is only necessary with `wait: true`
  - apiGroups:
      - apps
    resources:
      - replicasets
    verbs:
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-actions-demo
  namespace: github-actions-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: github-actions-demo
subjects:
  - kind: ServiceAccount
    name: github-actions-demo
    namespace: github-actions-demo