name: Pull Request Build
on:
  pull_request:
    branches: [ main ]

jobs:
  build-image:
    environment: default
    runs-on: ubuntu-latest
    steps:
      -   name: Checkout
          uses: actions/checkout@v3
      -   uses: actions/setup-java@v3
          with:
            distribution: 'temurin' # See 'Supported distributions' for available options
            java-version: '17'
      -   name: Build and export
          run: |
            #!/bin/bash
            mvn clean install -s settings.xml -B -Dmaven.repo.local=repo
            docker run -v `pwd`/repo:/repo -v `pwd`/target:/target quay.io/mk-ci-cd/apheleia-processor:b28d76bb3f9557daac3d88790a8bcfcea13139cd@sha256:9909955c908bdda9ac0089906d21bb0cfa558f5db3ef95ea29fc2d7b594971aa /opt/jboss/container/java/run/run-java.sh analyse --maven-repo=/repo /target/hacbs-test.jar --sbom-path /target/sbom.json || true
      -   uses: actions/upload-artifact@v3
          with:
            name: sbom.json
            path: target/sbom.json
