name: Pull Request Build
on:
  pull_request:
    branches: [ main ]

jobs:
  build-image:
    environment: default
    runs-on: ubuntu-latest
    steps:
      -   name: Checkout
          uses: actions/checkout@v3
      -   uses: actions/setup-java@v3
          with:
            distribution: 'temurin' # See 'Supported distributions' for available options
            java-version: '17'
      -   name: Build and export
          run: |
            #!/bin/bash
            mvn clean install -B -s settings.xml -Dmaven.repo.local=repo
            docker run -v `pwd`/repo:/repo -v `pwd`/target:/target quay.io/mk-ci-cd/apheleia-processor:df89a66314724604bd5be2112faea71d8bbbf0b6 /opt/jboss/container/java/run/run-java.sh analyse --maven-repo=/repo /target/hacbs-test.jar --sbom-path /target/sbom.json || true
            docker build . -t quay.io/sdouglas/spring-test:${{ github.sha }}
            docker push quay.io/sdouglas/spring-test:${{ github.sha }}
      -   uses: actions/upload-artifact@v3
          with:
            name: sbom.json
            path: target/sbom.json
